### ISSUE TITLE
Memory Usage Compressing and Encrypting Database

### ISSUE THREAD

**Issue by cwarden** [leijurv/gb#30]
I've been experimenting with gb on a server with 2GB of RAM and 3.5GB of swap.  It mostly works well, but `BackupDB()` causes a panic when memory can no longer be allocated, either during compression or encryption.

I was able get it working for a bit longer by switching from github.com/DataDog/zstd to tailscale.com/smallzstd and disabling the decryption and decompression verification, but with the SQLite database now at around 1GB, I'm back to running out of memory.

Backing up the database without having to read the whole file, and then compress it and encrypt it in memory, would be useful.

**Comment by leijurv** [comment]
ok I will make the database backup be streaming (like blob backup is) and not buffer the entire db in ram ever

**Comment by leijurv** [comment]
This is trickier than it looks - https://stackoverflow.com/questions/39378051/making-gcm-cbc-ciphers-streamable-in-golang and https://groups.google.com/g/golang-nuts/c/DLyC8UIJXa4?pli=1

I don't see a clear way to stream upload the database if golang's GCM doesn't support it.

**Comment by leijurv** [comment]
There are some methods outlined in those links, e.g. placing a MAC every 16 kilobytes, but then the new database backup would be incompatible with the old, which I don't like.

**Comment by leijurv** [comment]
I think I can get around this if I copy/paste large swaths of `crypto/cipher/gcm.go` (and `crypto/cipher/xor_generic.go`) into `gb` then modify it so that the internal state in `gcm.Seal` is stored in the `gcm` struct (specifically the `counter` that goes through `gcmInc32` within `gcm.counterCrypt`).

Downsides: icky, I might make a mistake, not confident in the security, not performant (wouldn't use the AESNI instructions anymore). but I feel like with a few unit tests I could be confident that it does encrypt properly. like, gcm mode is just ctr mode with a mac and nonce appended, so I could call the optimized ctr code (in theory) and only have the slow / insecure part be the generation of the mac and nonce, and I could verify that mac and nonce with unit tests?

But it would be compatible with the current backups, which would be cool. And it would be streaming. But if you're running it on a small VPS, then the overhead of non-hardware-accelerated AES / galois polynomial operations might make it still not worth it... idk

I will consider more later, this is more complicated than I thought it would be.
